name: 'Deploy to AWS S3'
description: 'Deploy the built website to AWS S3 bucket'
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket.'
    required: true
  app-artifact-name:
    description: 'The name of the (zipped) app artifact to download.'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website.'
runs:
  using: 'composite'
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.app-artifact-name }}
        path: .
    - name: Deploy to S3
      run: |
        unzip ${{ inputs.app-artifact-name }}
        npx aws-cli s3 sync . "s3://${{ inputs.bucket }}" --region "${{ inputs['bucket-region'] }}"
      shell: bash
