name: 'Deploy App'
description: 'Deploys app to Amazon S3 bucket and invalidates CloudFront cache'
inputs:
  test_value:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Logging Inputs For Testing
      run: |
        echo "appName: ${{ inputs.app_name }}"
        echo "environment: ${{ inputs.env }}"
      shell: bash

    - name: Call JS
      env:
        TEST_VALUE: ${{ inputs.test_value }}
      run: |
        node .github/actions/deploy-app/dist/index.js
      shell: bash
