name: 'Get & Cache Dependencies'
description: 'Get and cache dependencies for the project'
runs:
  using: 'composite'
  steps:
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: node-modules-yl-${{hashFiles('**/yarn.lock')}}-pk-${{ hashFiles('**/package.json') }}
    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: yarn install --immutable
    - name: Build website
      run: npx nx run react-app-1:build
      shell: bash
