name: Deploy Config

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Select the app config to deploy'
        required: true
        type: choice
        options:
          - react-app-1
run-name: Deploy Config for ${{ inputs.app-name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Upload config
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app-name }}
          path: libs/configs/src/configs/prod/${{ inputs.app-name }}.json
      - name: Download config artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.app-name }}
          path: .
      - name: Set CloudFront distribution ID
        id: set_cloudfront_distribution_id
        run: |
          if [ "${{ inputs.app-name }}" = "react-app-1" ]; then
            echo "value=ET94AF6UH5C6Z" >> $GITHUB_OUTPUT
          fi
      - name: Deploy to S3 bucket
        run: |
          aws s3 cp ${{ inputs.app-name }}.json s3://${{ secrets.CONFIGS_BUCKET }}/${{ inputs.app-name }}.json --region "${{ secrets.CONFIGS_REGION }}"
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ steps.set_cloudfront_distribution_id.outputs.value }} --paths "/${{ inputs.app-name }}.json"
