name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      run_optional_job:
        type: boolean

jobs:
  optional-job-1:
    runs-on: ubuntu-latest
    if: inputs.run_optional_job == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo Job 1
        run: |
          echo "Hello from Job 1"

  job-2:
    runs-on: ubuntu-latest
    needs: optional-job-1
    if: always() && (inputs.run_optional_job == false || needs.optional-job-1.result == 'success')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo Job 2
        run: |
          echo "Hello from Job 2"
