name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - prod
        description: 'The environment to deploy to'
        required: true
        default: 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./.github/actions/test-action
        with:
          test_value: 'Hello World'

  fake-deploy:
    name: 🚀 Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: 'https://example.com'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Deployment Via API
        id: create_deploy
        run: |
          DEPLOY_RESPONSE=$(gh api repos/${{ github.repository }}/deployments -f ref=${{ github.sha }} \
            -f environment=${{ inputs.environment }} \
            -f description="Deploy SHA ${{ github.sha }} by ${{ github.actor }}" \
            -f payload='{"version":"v1.0.0"}' \
            -f required_contexts='[]' \
            --jq '.id')
          echo "deployment_id=$DEPLOY_RESPONSE" >> $GITHUB_OUTPUT

      - name: Update deployment status
        run: |
          gh api repos/${{ github.repository }}/deployments/${{ steps.create_deploy.outputs.deployment_id }}/statuses \
            -f state=success \
            -f environment_url="https://my-app.example.com" \
            -f description="Deployment succeeded 🚀"
