name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - prod
        description: 'The environment to deploy to'
        required: true
        default: 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./.github/actions/test-action
        with:
          test_value: 'Hello World'

  fake-deploy:
    name: 🚀 Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: 'https://example.com'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Yay, it deployed to ${{ inputs.environment }}"
