name: Test Workflow
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./.github/actions/test-action
        with:
          test_value: 'Hello World'

  test-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          # optional artifact naem
          name: test-artifact
          # what to upload
          path: ./app/react-app-1/public/

      - name: Download Test Artifact
        uses: actions/download-artifact@v5
        with:
          # artifact name
          name: test-artifact
        #   # optional destination path, default is github workspace
        #   path: ./app/react-app-1/public

      - name: Display structure of downloaded files
        run: ls -R

      - name: Unzip Test Artifact
        run: unzip ./test-artifact -d /some-folder
